// <auto-generated />
using System;
using Hubex.Module.Adm.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hubex.Module.Adm.Migrations
{
    [DbContext(typeof(AdmDbContext))]
    partial class AdmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hubex.Module.Adm.Models.ListCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("PermissionExtId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ListCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionExtId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionExtId = 2
                        });
                });

            modelBuilder.Entity("Hubex.Module.Adm.Models.RolePermissionExt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("PermissionExtId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionExtId = 1,
                            RoleId = 1,
                            TenantId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionExtId = 2,
                            RoleId = 2,
                            TenantId = 1
                        });
                });

            modelBuilder.Entity("Hubex.Module.Adm.Models.TaskResponsibleUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TaskResponsibleUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TaskId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            TaskId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Hubex.Module.Adm.Models.TaskUserCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskListCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TaskUserCaches");
                });

            modelBuilder.Entity("Hubex.Module.Adm.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        });
                });

            modelBuilder.Entity("Hubex.Module.Adm.Models.UserDistrict", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("TenantId", "UserId", "DistrictId");

                    b.ToTable("UserDistricts");

                    b.HasData(
                        new
                        {
                            TenantId = 1,
                            UserId = 1,
                            DistrictId = 1,
                            Id = 1
                        },
                        new
                        {
                            TenantId = 1,
                            UserId = 2,
                            DistrictId = 2,
                            Id = 2
                        });
                });

            modelBuilder.Entity("Hubex.Module.Adm.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            TenantId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoleId = 1,
                            TenantId = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Hubex.Module.Adm.Models.UserTaskListCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TaskListCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserTaskListCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TaskListCategoryId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            TaskListCategoryId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Hubex.Module.Adm.Models.RolePermissionExt", b =>
                {
                    b.HasOne("Hubex.Module.Adm.Models.UserRole", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hubex.Module.Adm.Models.UserRole", b =>
                {
                    b.HasOne("Hubex.Module.Adm.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hubex.Module.Adm.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Hubex.Module.Adm.Models.UserRole", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
